//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WSLessons
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contract
    {
        public int Id { get; set; }
        public string ContractNumber { get; set; }
        public System.DateTime DateConclusionContract { get; set; }
        public string SupplierCompany { get; set; }
        public string RecipientCoumpany { get; set; }
        public decimal Sum { get; set; }
        public int RawCode { get; set; }
        public int CountryCode { get; set; }
    
        public virtual Country Country { get; set; }
        public virtual Raw Raw { get; set; }
    }
}
